<?php

// +----------------------------------------------------------------------
// | VMCSHOP [V M-Commerce Shop]
// +----------------------------------------------------------------------
// | Copyright (c) vmcshop.com All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.vmcshop.com/licensed)
// +----------------------------------------------------------------------
// | Author: Shanghai ChenShang Software Technology Co., Ltd.
// +----------------------------------------------------------------------
return array(
    // 默认
    '__' => array(
        'fields' => array(
            'goods_id' => 'goods_id',
            'goods_gid' => 'gid',
            'goods_name' => 'name',
            'goods_type_id' => 'type_id',
            'category_id' => 'cat_id',
            'brand_id' => 'brand_id',
            'market_able' => 'marketable',
            'goods_profile' => 'brief',
            'goods_content' => 'intro',
            'spec_desc' => 'spec_desc',
            'goods_setting' => 'goods_setting',
            //'products' => 'products',
            'profile_1' => 'p_1',
            'profile_2' => 'p_2',
            'profile_3' => 'p_3',
            'profile_4' => 'p_4',
            'profile_5' => 'p_5',
            'profile_6' => 'p_6',
            'profile_7' => 'p_7',
            'profile_8' => 'p_8',
            'profile_9' => 'p_9',
            'profile_10' => 'p_10',
            'profile_11' => 'p_11',
            'profile_12' => 'p_12',
            'profile_13' => 'p_13',
            'profile_14' => 'p_14',
            'profile_15' => 'p_15',
            'profile_16' => 'p_16',
            'profile_17' => 'p_17',
            'profile_18' => 'p_18',
            'profile_19' => 'p_19',
            'profile_20' => 'p_20',
            'profile_21' => 'p_21',
            'profile_22' => 'p_22',
            'profile_23' => 'p_23',
            'profile_24' => 'p_24',
            'profile_25' => 'p_25',
            'profile_26' => 'p_26',
            'profile_27' => 'p_27',
            'profile_28' => 'p_28',
            'profile_29' => 'p_29',
            'profile_30' => 'p_30',
            'profile_31' => 'p_31',
            'profile_32' => 'p_32',
            'profile_33' => 'p_33',
            'profile_34' => 'p_34',
            'profile_35' => 'p_35',
            'profile_36' => 'p_36',
            'profile_37' => 'p_37',
            'profile_38' => 'p_38',
            'profile_39' => 'p_39',
            'profile_40' => 'p_40',
            'profile_41' => 'p_41',
            'profile_42' => 'p_42',
            'profile_43' => 'p_43',
            'profile_44' => 'p_44',
            'profile_45' => 'p_45',
            'profile_46' => 'p_46',
            'profile_47' => 'p_47',
            'profile_48' => 'p_48',
            'profile_49' => 'p_49',
            'profile_50' => 'p_50',
        ),
        'output' => array(
        ),
    ),
    // goods.create - 创建商品 
    'create' => array(
        'fields' => array(
        ),
        'output' => array(
        ),
    ),
    // goods.update - 更新商品 
    'update' => array(
        'fields' => array(
            'goods' => array(
                'goods_id' => 'goods_id',
                'goods_gid' => 'gid',
                'goods_name' => 'name',
                'type_id' => 'type_id',
                'category_id' => 'cat_id',
                'brand_id' => 'brand_id',
                'market_able' => 'marketable',
                'goods_profile' => 'brief',
                'description' => 'intro',
                'specs' => 'spec_desc',
                //'products' => 'products',
                'profile_1' => 'p_1',
                'profile_2' => 'p_2',
                'profile_3' => 'p_3',
                'profile_4' => 'p_4',
                'profile_5' => 'p_5',
                'profile_6' => 'p_6',
                'profile_7' => 'p_7',
                'profile_8' => 'p_8',
                'profile_9' => 'p_9',
                'profile_10' => 'p_10',
                'profile_11' => 'p_11',
                'profile_12' => 'p_12',
                'profile_13' => 'p_13',
                'profile_14' => 'p_14',
                'profile_15' => 'p_15',
                'profile_16' => 'p_16',
                'profile_17' => 'p_17',
                'profile_18' => 'p_18',
                'profile_19' => 'p_19',
                'profile_20' => 'p_20',
                'profile_21' => 'p_21',
                'profile_22' => 'p_22',
                'profile_23' => 'p_23',
                'profile_24' => 'p_24',
                'profile_25' => 'p_25',
                'profile_26' => 'p_26',
                'profile_27' => 'p_27',
                'profile_28' => 'p_28',
                'profile_29' => 'p_29',
                'profile_30' => 'p_30',
                'profile_31' => 'p_31',
                'profile_32' => 'p_32',
                'profile_33' => 'p_33',
                'profile_34' => 'p_34',
                'profile_35' => 'p_35',
                'profile_36' => 'p_36',
                'profile_37' => 'p_37',
                'profile_38' => 'p_38',
                'profile_39' => 'p_39',
                'profile_40' => 'p_40',
                'profile_41' => 'p_41',
                'profile_42' => 'p_42',
                'profile_43' => 'p_43',
                'profile_44' => 'p_44',
                'profile_45' => 'p_45',
                'profile_46' => 'p_46',
                'profile_47' => 'p_47',
                'profile_48' => 'p_48',
                'profile_49' => 'p_49',
                'profile_50' => 'p_50',
            ),
            'filter' => array(
                'goods_id' => 'goods_id',
            ),
        ),
        'output' => array(
        ),
    ),
    // goods.delete - 删除商品 
    'delete' => array(
        'fields' => array(
            'goods_id' => 'goods_id',
        ),
        'output' => array(
        ),
    ),
);
